INSERT INTO vets VALUES (default, 'James', 'Carter');
INSERT INTO vets VALUES (default, 'Helen', 'Leary');
INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (default, 'radiology');
INSERT INTO specialties VALUES (default, 'surgery');
INSERT INTO specialties VALUES (default, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'cat');
INSERT INTO types VALUES (default, 'dog');
INSERT INTO types VALUES (default, 'lizard');
INSERT INTO types VALUES (default, 'snake');
INSERT INTO types VALUES (default, 'bird');
INSERT INTO types VALUES (default, 'hamster');

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');

/*
 CREATE TABLE calendar (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_fk   INTEGER,
    name        VARCHAR(255),
    start       DATETIME,
    "end"       DATETIME, -- end is keyword, MySQL uses backtick '
    link        VARCHAR(255), -- DEFAULT NULL
    meta        VARCHAR(255)
);

CREATE TABLE artist (
    artistid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencyid   INT,
    artistcontent   VARCHAR(100),
    artistCount   INT
);

CREATE TABLE agency (
    agencyId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencyName varchar(255)
);
 */
INSERT INTO agency VALUES (1, 'hive');
INSERT INTO artist VALUES (1, 1, 'BTS', 'BTS is great', 'image.jpg', 100);
--INSERT INTO calendar VALUES (1, 1, 'BTS-A Meeting', '2024-02-12 12:30:00', '2024-02-14 14:45:00', 'http://www.sbs.co.kr', '');
--INSERT INTO calendar VALUES (100, 1, 'BTS-A Meeting', '2024-02-09 12:30:00', '2024-02-09 14:45:00', 'http://www.sbs.co.kr', '');
/*
INSERT INTO calendar VALUES (1, 1, 'BTS-A Meeting', '2024-01-31 12:30:00', '2024-01-31 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (2, 1, 'BTS-B Meeting', '2024-02-01 12:30:00', '2024-02-01 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (3, 1, 'BTS-C Meeting', '2024-02-13 12:30:00', '2024-02-13 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (4, 1, 'BTS-C Meeting', '2024-02-14 12:30:00', '2024-02-14 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (5, 1, 'BTS-C Meeting', '2024-02-15 12:30:00', '2024-02-15 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (6, 1, 'BTS-C Meeting', '2024-02-16 12:30:00', '2024-02-16 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (7, 1, 'BTS-C Meeting', '2024-02-17 12:30:00', '2024-02-17 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (8, 1, 'BTS-E Meeting', '2024-02-29 12:30:00', '2024-02-29 14:45:00', 'http://www.sbs.co.kr', '');
INSERT INTO calendar VALUES (9, 1, 'BTS-F Meeting', '2024-03-01 12:30:00', '2024-03-02 14:45:00', 'http://www.sbs.co.kr', '');
*/
